### ISSUE TITLE
git bash cursor disappears after running goful

### ISSUE THREAD

**Issue by davmaz** [anmitsu/goful#12]
### To Reproduce:
1. Input key '....'
2. Processing '....'
3. See error

### Desktop (please complete the following information):
* OS: 
* Terminal

**Comment by davmaz** [comment]
Reproduce:
On Windows 10 using gitbash 'shell'
run goful
Exit (q)
After exiting, the gitbash shell prompt no longer shows a cursor AND
  commands cannot be edited, etc.

Desktop:
 Windows 10
 gitbash console/shell

**Comment by anmitsu** [comment]
@davmaz 
I don't usually use windows so thanks for this issue.
Please wait for a while until it is fixed.
