### ISSUE TITLE
Provide pre built releases for the major platforms

### ISSUE THREAD

**Issue by breml** [anmitsu/goful#13]
### Describe the solution you'd like

It would be very convenient if this project could provide pre built releases for the major platforms e.g. via GoReleaser. Installing it via go get -u or git clone and then use the custom build script is not optimal.

**Comment by anmitsu** [comment]
@breml Thanks for your opinion.

I consider providing pre build releases.
For now, GoReleaser + GitHub Action looks good.
Please let me know if there are other solutions.

**Comment by anmitsu** [comment]
This project provided pre-build releases by Goreleaser and GitHub Action.
