### ISSUE TITLE
Multiple errors...

### ISSUE THREAD

**Issue by bdaniel7** [anmitsu/goful#3]
I'm trying to get goful but I can't.

λ go version
go version go1.15.7 windows/amd64 (Windows 10 Pro x64)

λ go get github.com/anmitsu/goful
# runtime
C:\programs\Go\src\runtime\hashmap.go:89:2: empty redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\chan.go:428:22
C:\programs\Go\src\runtime\map.go:65:2: bucketCntBits redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:64:18
C:\programs\Go\src\runtime\map.go:66:2: bucketCnt redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:65:23
C:\programs\Go\src\runtime\map.go:77:2: maxKeySize redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:74:17
C:\programs\Go\src\runtime\map.go:83:2: dataOffset redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:83:4
C:\programs\Go\src\runtime\map.go:94:2: evacuatedX redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:91:19
C:\programs\Go\src\runtime\map.go:95:2: evacuatedY redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:92:19
C:\programs\Go\src\runtime\map.go:96:2: evacuatedEmpty redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:90:19
C:\programs\Go\src\runtime\map.go:97:2: minTopHash redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:93:19
C:\programs\Go\src\runtime\map.go :100 :2: iterator redeclared in this block
        previous declaration at C:\programs\Go\src\runtime\hashmap.go:96:17
C:\programs\Go\src\runtime\map.go :100 :2: too many errors

**Comment by anmitsu** [comment]
This issue may be same as https://github.com/golang/go/issues/27269

Please delete old go version and re-install the new one may be fix the issue.

Thanks

**Comment by bdaniel7** [comment]
Right. I initially installed 1.15.7 over the old version. Now I uninstalled 1.15.7, removed all files from the install directory, then installed 1.15.7 again, and now I was able to get goful working.

Thanks.
