### ISSUE TITLE
adding personal bookmarks

### ISSUE THREAD

**Issue by go-dockly** [anmitsu/goful#4]
Hi 

first of all great project I am already using it every day ^^

It would be great to have the ability to add ones own bookmarks to the predefined list at main.go:242

**Comment by anmitsu** [comment]
Thanks for using.

You can directly edit `main.go` for adding personal bookmarks.

I recommend to create own customizable `main.go` leaving the original.

Own `my/goful/main.go` creation example:

    Go to the project path
    $ cd $GOPATH/src/github.com/anmitsu/goful

    Copy original main.go to my/goful directory
    $ mkdir -p my/goful
    $ cp main.go my/goful
    $ cd my/goful
    
    After edited my/goful/main.go
    $ go install

Note that the directory name of `main.go` becomes binary file name.
